### ISSUE TITLE
Format for token or token_file

### ISSUE THREAD

**Issue by mzac** [ITRS-Group/check_k8s#23]
Hi, I'm trying to get your plugin to work.  I created a service account in my cluster and downloaded the configuration file for the account but it does not like it.

What is the format that is required for the token_file?  Like this?

```
apiVersion: v1
kind: Config
clusters:
  - name: default
    cluster:
      server: 'https://192.168.0.60:6443'
      certificate-authority-data: >-
        blahblahblah
users:
  - name: icinga
    user:
      token: >-
        tokendatatokendatatokendata
contexts:
  - name: default
    context:
      user: icinga
      cluster: default
      namespace: default
current-context: default
```
