### ISSUE TITLE
State "Completed" should be ignored by the check

### ISSUE THREAD

**Issue by yw5vruox7dr** [ITRS-Group/check_k8s#35]
When you start a K8s CronJob and it finishes - the pod remains until you manually clear it away.
  The status is "0/1 Completed" - since this is not an error, this should be considered healthy.

For example:
```yaml
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: awx-postgres-backup
  namespace: awx-ext
spec:
  schedule: "50 19 * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: gitlab-postgres-backup-auth
          restartPolicy: OnFailure
          containers:
            - name: awx-postgres-backup
              image: xxx/postgres_backup:latest
              command: ["/bin/sh"]
              args:
                - -c
                - [...]
```
```bash
k8s-int-master01 ~ # kubectl create job --from=cronjob/awx-postgres-backup manual -n awx-ext
job.batch/manual created

k get pods | grep -e STATUS -e manual
NAME                                               READY   STATUS      RESTARTS   AGE
manual-z8zcm                                       0/1     Completed   0          34s

kubectl delete job.batch/manual -n awx-ext
job.batch "manual" deleted
```

Currently it results in:
```
Pod manual-z8zcm: condition [not] Ready since 2022-04-01T16:40:04Z
```
