### ISSUE TITLE
Improve documentation regarding kubernetes permissions

### ISSUE THREAD

**Issue by hanswurscht** [ITRS-Group/check_k8s#54]
Hi,

first of all: nice check!

I wanted to monitor our pods and tried the following permission rule without success (`UNKNOWN - 401: Unauthorizedt`):
````
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "list"]
````

Can you please improve the documentation?
The minimal needed permissions for connecting to kubernetes should be written somewhere. 

Thanks!
- Lorenz

**Comment by hanswurscht** [comment]
Hi,

it was my fault. I needed to base64-decode the secret first before using it :)

Regarding the permissions. This works now for pods and deployments:

````
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: role-monitoring-icinga-readonly
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - list
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - list
````
